---
title: "The Good Country"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    social: [ menu ]
    #source_code: embed
    vertical_layout: fill
runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)

library(readr)
library(plotly)
library(DT)

library(vembedr)

library(dplyr)

# all data
data <- read_csv("data/data2011.csv")
#data$Overall_Rank <- as.numeric(data$Overall_Rank)
glossary <- read_csv("data/glossary.csv")

# standard map criteria
# light grey boundaries
l <- list(color = toRGB("grey"), width = 0.5)

# specify map projection/options
g <- list(
  showframe = FALSE,
  showcoastlines = TRUE,
  projection = list(type = 'robinson')
)
```


Inputs {.sidebar data-width=375}
-------------------------------------

```{r inc munging}
includeMarkdown("info.md")
hr()
embed_youtube("1X7fZoDs9KU", width=350, query = list(start = secs("11m12s")))
hr()
includeMarkdown("licence.md") 


inputPanel(
radioButtons("category", label="Select Category",
             choices=c("Overall",
                       "Science & Technology",
                       "Culture",
                       "Peace & Security",
                       "World Order",
                       "Planet & Climate",
                       "Prosperity & Equality",
                       "Health & Wellbeing"), inline=T)
)


```



Column {data-width=3 }
-----------------------------------------------------------------------

###  {.no-title}

```{r munging}

info <- reactive({
  
if(input$category=="Overall")  {
  print("enter overall")
df <- data[c(1:163),c(1,2,3:10)]

df$hover <- with(df, paste(Country, '<br>', "Overall", Overall_Rank, "<br>", "Science/Tech", ST_Rank, "<br>",
                                       "Culture", CU_Rank, "<br>", "Peace/Security", PS_Rank,
                                       "<br>", "World Order", WO_Rank,  "<br>","Climate", PC_Rank, "<br>",
                                       "Prosperity", PE_Rank,  "<br>","Health", HW_Rank))

} else if (input$category=="Science & Technology") {

df <- data[c(1:163),c(1,2,4,11:15,46)]

df$hover <- with(df, paste(Country, '<br>', "Overall", ST_Rank, "<br>", "Int Students", ST11, "<br>",
                                       "Journal Exports", ST12, "<br>", "Publications", ST13,
                                       "<br>", "Nobel Prizes", ST14,  "<br>","Patents", ST15))


} else if (input$category=="Culture") {

df <- data[c(1:163),c(1,2,5,16:20,47)]

df$hover <- with(df, paste(Country, '<br>', "Overall", CU_Rank, "<br>", "Creative Goods Exports", CU21, "<br>",
                                       "Creative Services Exports", CU22, "<br>", "UNESCO dues in arrears", CU23,
                                       "<br>", "Freedom of Movement", CU24,  "<br>","Press Freedom", CU25))


} else if (input$category=="Peace & Security") {

df <- data[c(1:163),c(1,2,6,21:25,48)]

df$hover <- with(df, paste(Country, '<br>', "Overall", PS_Rank, "<br>", "Peacekeeping Troops", PS31, "<br>",
                                       "Peacekeeping Dues Arrears", PS32, "<br>", "International Conflicts", PS33,
                                       "<br>", "Arms Exports", PS34,  "<br>","Internet Security", PS35))


}  else if (input$category=="World Order") {

df <- data[c(1:163),c(1,2,7,26:30,49)]

df$hover <- with(df, paste(Country, '<br>', "Overall", WO_Rank, "<br>", "Charity Giving", WO41, "<br>",
                                       "Refugees Hosted", WO42, "<br>", "Refugees Generated", WO43,
                                       "<br>", "Birth Rate", WO44,  "<br>","UN Treaties Signed", WO45))


}

  else if (input$category=="Planet & Climate") {

df <- data[c(1:163),c(1,2,8,31:35,50)]

df$hover <- with(df, paste(Country, '<br>', "Overall", PC_Rank, "<br>", "Ecological Footprint", PC51, "<br>",
                                       "Reforestation since 1992", PC52, "<br>", "HazPest Exports", PC53,
                                       "<br>", "CO2 Emissions", PC54,  "<br>","Ozone", PC55))


}
else if (input$category=="Prosperity & Equality") {

df <- data[c(1:163),c(1,2,9,36:40,51)]

df$hover <- with(df, paste(Country, '<br>', "Overall", PE_Rank, "<br>", "Open Trading", PE61, "<br>",
                                       "UN Volunteers Abroad", PE62, "<br>", "Fairtrade market size", PE63,
                                       "<br>", "FDI Outflows", PE64,  "<br>","Development Assistance", PE65))


} else if (input$category=="Health & Wellbeing") {

df <- data[c(1:163),c(1,2,10,41:45,52)]

df$hover <- with(df, paste(Country, '<br>', "Overall", HW_Rank, "<br>", "Food Aid", HW71, "<br>",
                                       "Pharmaceutical exports", HW72, "<br>", "Voluntary excess donations to the WHO", HW73,
                                       "<br>", "Humanitarian aid donations", HW74,  "<br>","Int. Health Regs Compliance", HW75))


}

  
  
  
 # (glimpse(df))
  info=list(df=df)
  return(info)

})



renderPlotly({
  
  req(info())
  
  theTitle <- paste0(input$category," Index - Hover for Details")
  
  df <-info()$df
  
  if(input$category=="Overall")  {
   
  
p <- df %>% 
        plot_ly( z = Overall_Rank, text = hover, locations = ISOcode, type = 'choropleth',
        color = Overall_Rank, colors = 'RdYlGn', marker = list(line = l), showscale=F, reversescale = TRUE
) 
} else if (input$category=="Science & Technology") {
  p <- df %>% 
        plot_ly( z = ST_Rank, text = hover, locations = ISOcode, type = 'choropleth',
        color = ST_Rank, colors = 'RdYlGn', marker = list(line = l), showscale=F, reversescale = TRUE
) 
}  else if (input$category=="Culture") {
  p <- df %>% 
        plot_ly( z = CU_Rank, text = hover, locations = ISOcode, type = 'choropleth',
        color = CU_Rank, colors = 'RdYlGn', marker = list(line = l), showscale=F, reversescale = TRUE
) 
} else if (input$category=="Peace & Security") {
  p <- df %>% 
        plot_ly( z = PS_Rank, text = hover, locations = ISOcode, type = 'choropleth',
        color = PS_Rank, colors = 'RdYlGn', marker = list(line = l), showscale=F, reversescale = TRUE
) 
}
  
  else if (input$category=="World Order") {
  p <- df %>% 
        plot_ly( z = WO_Rank, text = hover, locations = ISOcode, type = 'choropleth',
        color = WO_Rank, colors = 'RdYlGn', marker = list(line = l), showscale=F, reversescale = TRUE
) 
  }
  
   else if (input$category=="Planet & Climate") {
  p <- df %>% 
        plot_ly( z = PC_Rank, text = hover, locations = ISOcode, type = 'choropleth',
        color = PC_Rank, colors = 'RdYlGn', marker = list(line = l), showscale=F, reversescale = TRUE
) 
   }
  
     else if (input$category=="Prosperity & Equality") {
  p <- df %>% 
        plot_ly( z = PE_Rank, text = hover, locations = ISOcode, type = 'choropleth',
        color = PE_Rank, colors = 'RdYlGn', marker = list(line = l), showscale=F, reversescale = TRUE
) 
     }
  
       else if (input$category=="Health & Wellbeing") {
  p <- df %>% 
        plot_ly( z = HW_Rank, text = hover, locations = ISOcode, type = 'choropleth',
        color = HW_Rank, colors = 'RdYlGn', marker = list(line = l), showscale=F, reversescale = TRUE
) 
}
  
p %>%
  layout(title = theTitle,
         geo = g)
})
```


Column {data-width=2 .tabset}
-----------------------------------------------------------------------

<!-- Row {data-height=5} -->
<!-- ------------------------------------- -->

### 2011 index 

``` {r}

DT::renderDataTable({
  
 if(input$category=="Overall")  {
df <-  info()$df %>% 
    select(Country,Science=ST_Rank,Culture=CU_Rank,Peace=PS_Rank,Order=WO_Rank,Climate=PC_Rank,Prosperity=PE_Rank,Health=HW_Rank)

} else if (input$category=="Science & Technology") {
  df <-  info()$df %>% 
    arrange(ST_Rank) %>% 
  select(Country,Total=ST,ST11,ST12,ST13,ST14,ST15)
  
} else if (input$category=="Culture") {
  df <-  info()$df %>% 
    arrange(CU_Rank) %>% 
  select(Country,Total=CU,CU21,CU22,CU23,CU24,CU25)

  
} else if (input$category=="Peace & Security") {
  df <-  info()$df %>% 
    arrange(PS_Rank) %>% 
  select(Country,Total=PS,PS31,PS32,PS33,PS34,PS35)
  
} else if (input$category=="World Order") {
  df <-  info()$df %>% 
    arrange(WO_Rank) %>% 
  select(Country,Total=WO,WO41,WO42,WO43,WO44,WO45)

    
} else if (input$category=="Planet & Climate") {
  df <-  info()$df %>% 
    arrange(PC_Rank) %>% 
  select(Country,Total=PC,PC51,PC52,PC53,PC54,PC55)

  
} else if (input$category=="Prosperity & Equality") {
  df <-  info()$df %>% 
    arrange(PE_Rank) %>% 
    mutate(PE=round(PE,2),
           PE61=round(PE61,2),
           PE62=round(PE62,2),
           PE63=round(PE63,2),
           PE64=round(PE64,2),
           PE65=round(PE65,2)) %>% 
  select(Country,Total=PE,PE61,PE62,PE63,PE64,PE65)

  
} else if (input$category=="Health & Wellbeing") {
  df <-  info()$df %>% 
    arrange(HW_Rank) %>% 
  select(Country,Total=HW,HW71,HW72,HW73,HW74,HW75)
}
  
  df %>% 
  DT::datatable(class='compact stripe hover row-border order-column',rownames=TRUE,options= list(pageLength = 20, paging = TRUE, searching = TRUE,info=FALSE))
    
})



```


<!-- Row {data-height=1} -->
<!-- ------------------------------------- -->

### Glossary 


<!-- For more detailed information on codes refer to this [Google Sheet](https://docs.google.com/spreadsheets/d/1SPeyQBIRYqXRIczMs5xixd329u-rFONvf4Wbi1eC_iI/edit#gid=544960824) -->

``` {r glossary}

includeMarkdown("index.md")


DT::renderDataTable({
  glossary %>%
DT::datatable(class='compact stripe hover row-border order-column',rownames=FALSE,options= list(pageLength=7,paging = TRUE, searching = TRUE,info=FALSE))
})

```